version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      DB_URL: jdbc:postgresql://db:5432/abrigochuva
      DB_USER: postgres
      DB_PASSWORD: 123
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: abrigochuva
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
